# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: eu.gcr.io/census-eq-ci/eq-address-lookup-api
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80

ingress:
  enabled: true

resources:
  cpu: "3"
